version: '2'
services:
  app:
    build: .
    volumes:
      - "./:/opt/app"
    ports:
      - 8000
    links:
      - rethinkdb
    environment:
      IS_DOCKER: 'TRUE'
      PORT: 8000
  rethinkdb:
    image: rethinkdb
